using System;

namespace EvolutionSimulation
{
    /// <summary>
    /// Plant generated by the map's flora.
    /// Provides sustenance and physicial interaction
    /// </summary>
    public abstract class Plant : IEntity
    {
        abstract public void Tick();
    }
}