using System;

namespace EvolutionSimulation.Entities
{
    /// <summary>
    /// Plant generated by the map's flora.
    /// Provides sustenance and physicial interaction
    /// </summary>
    public abstract class Plant : StaticEntity
    {
        public new int x { get; private set; }
        public new int y { get; private set; }

        virtual public new void Tick()
        {
            throw new NotImplementedException();
        }
    }
}