using System;

namespace EvolutionSimulation.Entities
{
    /// <summary>
    /// Plant generated by the map's flora.
    /// Provides sustenance and physicial interaction
    /// </summary>
    public class Plant : StaticEntity
    {
        public enum PlantType
        {
            Grass,
            Bush,
            Tree,
            EdibleTree
        }

        public PlantType type;
        //public new int x { get; private set; }
        //public new int y { get; private set; }
    }
}