using System;

namespace AlgoritmoEvolutivo
{
    /// <summary>
    /// Plant generated by the map's flora.
    /// Provides sustenance and physicial interaction
    /// </summary>
    public class Plant : IEntity
    {
        public void Tick()
        {
            throw new NotImplementedException();
        }
    }
}